### ISSUE TITLE
[feature] Use caicloud/nirvana since it supports reverse proxy now

### ISSUE THREAD

**Issue by gaocegege** [kleveross/temp-model-registry#34]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

Ref https://github.com/caicloud/nirvana/pull/342

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by simon-cj** [comment]
There are two problem

- nirvana MUST support HEAD HTTP Method https://github.com/caicloud/nirvana/issues/273

- nirvana NEED support ALL option for HTTP Method https://github.com/caicloud/nirvana/issues/343

so, can not use nirvina right, must wait nirvina support https://github.com/caicloud/nirvana/issues/273

**Comment by gaocegege** [comment]
Gotcha

Can nirvana support regex?

**Comment by simon-cj** [comment]
Yes, regex is ok
